import HeadMeta from '../../core-components/head.meta'
import styles from '../../styles/Home.module.css'
import Breadcrumb from '../../components/breadcrumb'
export default function Photos() {
  const pageTitle = "Photos"
   //dropdown Json Format
   const breadcrumb=[
      { text: 'Home', link: '/' },
      { text: 'All Photos', isCurrentStep: true }
  ]
  
  const photos=[
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Malaika Arora Saree Look",
          "rsId":null,
          "description":"",
          "title":"Malaika Arora Saree Look ",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":1642,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear",
          "is_pic_verified":true,
          "tag_name":"latest saree trends,designer sarees,malaika aror sarees,bridal sarees,sarees for wedding,bollywood celeb looks,bollywood wedding styles,bridesmaid look,celeb looks,celebrity fashion trends,blouse design ideas,temple jewelery",
          "metaDesc":"Bridal Saree designs, designer saree designs, latest bridal saree images & trends - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/3d5ebc54-e75b-c277-500e-8dc5ceac0212.jpeg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"mandala henna designs",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/06\/15\/minimalistic-mandala-mehendi-designs\/\" target=\"_blank\">Minimalistic Mandala Mehendi Designs For Intimate Weddings!<\/a>.<\/p>\r\n",
          "title":"Bridal Latest Backhand Henna",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Destination Wedding",
          "id":5990,
          "swPhotos":null,
          "vendorCategory":"Mehendi Designs",
          "is_pic_verified":true,
          "tag_name":"bridal latest backhand henna,bridal backhand mehendi,bridal backhand mehendi design,bridal mandala mehendi,mandala mehndi designs,bridal mehndi designs,bridal mehndi designs for hands,arabic mehndi designs & pakistani mehndi designs,bridal mehendi,bridal mehendi design ideas,geometrical mehndi designs,henna design ideas,intricate mehendi designs,mandala henna designs,mandala mehendi designs,mehendi designs for brides and bridesmaids,minimalistic mehendi designs,simple mehandi designs,symmetrical mehndi designs",
          "metaDesc":"Bridal mehndi designs, Bridal mehndi designs for hands, Arabic mehndi designs & Pakistani mehndi designs - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Mehendi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/7189db17-a717-539f-3fc2-9a720d2f35e6.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"metallic lehenga",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/08\/18\/stunning-roka-outfits-spotted-on-real-brides\/\" target=\"_blank\">Stunning Roka Outfits Spotted On Real Brides<\/a>.<\/p>\r\n",
          "title":"silver shimmery metallic lehenga",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":6780,
          "swPhotos":null,
          "vendorCategory":"Make Up and Hair,Bridal Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"bridal wear,bridal outfit,Roka Outfit,roka outfit ideas,roka ceremony,roka dress,bridal lehenga,Silver Lehenga,shimmery lehenga,metallic lehenga,lehenga twirling bride,bridal portrait,wedding photography,bridal photoshoot,single dupatta lehenga",
          "metaDesc":"Bridal lehenga designs, designer lehenga designs, latest bridal lehenga images & trends - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Roka",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/addef416-0271-587b-93cb-640b3e1f0d2f.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"beach wedding ideas",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/02\/14\/amazing-beach-mandap-decor-ideas-for-your-destination-wedding\/\" target=\"_blank\">Amazing Beach Mandap Decor Ideas For Your Destination Wedding!<\/a>.<\/p>\r\n",
          "title":"beach mandap decor ideas",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Beach Wedding",
          "id":4991,
          "swPhotos":null,
          "vendorCategory":"Decor,Wedding Photography,Unique Ideas",
          "is_pic_verified":true,
          "tag_name":"beach wedding,mandap decor,beach mandap decor,beach mandap decor ideas,beach wedding mandap,beachside mandap,beach wedding ideas,mandap decor ideas,destination wedding,Wedding decor,decor,decor ideas,decor trends 2020,decor photography,wedding photography,photography ideas",
          "metaDesc":"Indian wedding decoration ideas & designs, wedding mandap designs and photos, wedding stage designs & photos and flower decor ideas - get latest & popular designs, ideas & inspirations for your wedding decor.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/8e873998-b227-029e-2cf1-8617f55fb79d.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Saptapadi Rituals",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2021\/02\/01\/marathi-wedding-rituals\/\" target=\"_blank\">Everything You Need To Know About Marathi Wedding Rituals<\/a>.<\/p>\r\n",
          "title":"Bride & Groom Taking Pheras",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":9983,
          "swPhotos":null,
          "vendorCategory":"Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"marathi wedding rituals,maharashtrian wedding,Wedding Rituals,saptapadi ceremony,wedding ceremony,wedding vows,Wedding Customs,traditions,wedding pheras,bride,Groom",
          "metaDesc":"Explore 1000s of wedding & bridal photos and save ideas for your wedding. Start exploring from Shaadiwish gallery and follow the latest designs and trends to plan a perfect wedding. ",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/b7992711-e0a1-ba68-c1c0-71423dbbe903.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"floral mehendi designs",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/12\/21\/best-mehendi-designs-for-brides\/\" target=\"_blank\">Best Mehendi Designs Of 2020 We Spotted On Real Brides<\/a>.<\/p>\r\n",
          "title":"Personalized Floral Mehendi Design",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"South Indian Weddings",
          "id":9166,
          "swPhotos":null,
          "vendorCategory":"Mehendi Designs",
          "is_pic_verified":true,
          "tag_name":"best mehendi designs,bridal henna designs,bridal mehandi designs,bridal mehndi designs,bridal trends,henna designs for brides,latest mehndi designs,mehandi trends,mehendi designs,mehendi ideas,portrait mehendi designs",
          "metaDesc":"Bridal mehndi designs, Bridal mehndi designs for hands, Arabic mehndi designs & Pakistani mehndi designs - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Mehendi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/a377f5ec-f4f5-6e3f-22f0-685e2b6c808d.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"redbanarasisaree",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/12\/12\/bridal-necklace-designs\/\" target=\"_blank\">30 Bridal Necklace Designs For A Stellar Look<\/a>.<\/p>\r\n",
          "title":"red banarasi saree with gold jewellery",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Palace Wedding",
          "id":8884,
          "swPhotos":null,
          "vendorCategory":"Jewellery,Make Up and Hair,Bridal Wear,Wedding Photography,Unique Ideas",
          "is_pic_verified":true,
          "tag_name":"Bridal Saree,banarasi saree,red banarasi saree,bridal hairstyle,gajra hairstyle,gajra bun,bridal portrait,wedding photography,bridal necklace designs,bridal necklace set,wedding necklace,wedding necklace set,bridal jewellery ideas,Gold Jewellery,gold necklace,Maang Tikka,kade",
          "metaDesc":"Bridal jewellery designs, latest bridal jewellery designs, - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/5b27004e-f6b9-e63e-5d26-b21c21687569.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"wedding invite",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/09\/18\/an-assamese-marwadi-wedding-with-cutesy-diy-elements\/\" target=\"_blank\">This Assamese-Marwadi Wedding With Cutesy DIY Elements Will Make You Fall In Love!<\/a>.<\/p>\r\n",
          "title":"DIY Wedding Invite Ideas",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Multicultural Weddings",
          "id":7658,
          "swPhotos":null,
          "vendorCategory":"Invitations",
          "is_pic_verified":true,
          "tag_name":"diy wedding invite ideas,wedding card ideas,wedding invite,customized wedding invite,wedding card,wedding card designs,unique wedding card,wedding invitations,wedding invite design,wedding invite ideas,wedding trends,weddings 2020,caricature invites,quirky wedding invite,wedding invitation card ideas",
          "metaDesc":"Browse ShaadiWish for latest wedding trends on invitations, favours, accessories and other wedding planning themes and ideas.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/0abf1926-411e-e8bc-dad4-ae311cab646a.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"The Wedding Files",
                "inspiration_id":7658,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":0,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"The Wedding Files",
                   "vendor_category_name":"Wedding Photographers",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":1615,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/a1df86c6-da90-4da6-a5d8-09a2c1b09a2d.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":1615,
                "album_id":null,
                "comment":"",
                "id":9343,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"sikh wedding couple",
          "rsId":null,
          "description":"<p>Jagmeet SIngh Anand Karaj.&nbsp;<\/p>\r\n",
          "title":"Jagmeet Singh Wedding Photos ",
          "no_of_likes":26,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Sikh Weddings",
          "id":871,
          "swPhotos":null,
          "vendorCategory":"Make Up and Hair,Bridal Wear,Groom Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"sikh wedding,Indian Wedding,Wedding Rituals,couple,couple goals,bride,Groom,Real Shaadis,Real Bride,Gurudwara Wedding,family,love,Wedding Guests,friends,bridal lehenga,katar,wedding jewelery,bridal jewelery,Jewellery,jewellery ideas,wedding photography,Wedding Inspiration,wedding ideas,wedding inspo,Wedding planning,Real Groom,jagmeet singh canada,gurkiran kaur,NRI Wedding,destination wedding,sikh couple portrait,sikh couple wedding photography,Punjabi Couple,Punjabi wedding,color coordinated outfit,couple wedding portrait,punjabi couple wedding photography,punjabi couple wedding portrait",
          "metaDesc":"Browse a variety of wedding pictures and photos at ShaadiWish. Search by location, color, theme and more.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/f4d3de32-dae7-4d4d-ad4d-2a3171d0adb0.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"bridal jewellery",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/02\/08\/gorgeous-oversized-jewellery-pieces-that-we-spotted-on-real-brides\/\" target=\"_blank\">Gorgeous Oversized Jewellery Pieces That We Spotted On Real Brides!<\/a>.<\/p>\r\n",
          "title":"Oversized Maang Tikka & A Heavy Bridal Necklace",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":4673,
          "swPhotos":null,
          "vendorCategory":"Jewellery,Make Up and Hair,Bridal Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"Bridal Jewellery,Jewellery,jewellery designs,latest jewellery designs,trending jewellery,oversized jewellery,bridal portrait,portrait ideas,bridal photoshoot,oversized maang tikka,hevay necklace,earrings,Bridal makeup,bridsl suit,bridal trends,Punjabi wedding,punjabi bride",
          "metaDesc":"Bridal jewellery designs, latest bridal jewellery designs, - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/05875210-60dc-4b06-49c3-d01e4bac542c.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Kohl eyes by Jo",
                "inspiration_id":4673,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":0,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"Kohl eyes by Jo",
                   "vendor_category_name":"Bridal Makeup",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":1512,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/05ffa4ae-a2a4-4d36-b3ca-6795f52e2dbb.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":1512,
                "album_id":null,
                "comment":"",
                "id":8006,
                "category":"Bridal Makeup",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"floralkaleeras",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/06\/30\/bridal-floral-kaleeras\/\" target=\"_blank\">The Most Unique and Lovely Floral Kaleeras For Brides-To-Be<\/a>.<\/p>\r\n",
          "title":"gorgeous white roses kalire",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Multicultural Weddings",
          "id":8095,
          "swPhotos":null,
          "vendorCategory":"Jewellery,Wedding Accessories",
          "is_pic_verified":true,
          "tag_name":"bridal kalire,bridal kaleere,floral kalire,floral bridal kalire,floral bridal kaleere,Floral Jewellery,bridal floral jewellery,Bridal Accessories,wedding accessories,bridal trends,white floral kalire,bridal bangles,detailed photography,wedding photography,photography ideas",
          "metaDesc":"Bridal jewellery designs, latest bridal jewellery designs, - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/100e96f2-a34f-4849-901b-f156a7851cc8.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"haldi ",
          "rsId":null,
          "description":"",
          "title":"Haldi Photo Ideas",
          "no_of_likes":18,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":492,
          "swPhotos":null,
          "vendorCategory":"Wedding Photography,Unique Ideas",
          "is_pic_verified":true,
          "tag_name":"Haldi,Haldi Ceremony,haldi outfit,North Indian Weddings,ceremonies,flower shower,floral jewelry,bride to be,haldi photo ideas,Floral Jewellery,Haldi Photos,Roses,guests showering rose petals,haldi portrait,haldi rituals,haldi rituals photography,bridal haldi portrait,bridal haldi photography,bridal haldi rituals,haldi unique ideas",
          "metaDesc":"Explore 1000s of wedding & bridal photos and save ideas for your wedding. Start exploring from Shaadiwish gallery and follow latest designs and trends to plan a perfect wedding. ",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Haldi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/7d548eba-7745-4f89-821f-4566272fe374.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":" Himanshu Jangid Photography",
                "inspiration_id":492,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":5,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":" Himanshu Jangid Photography",
                   "vendor_category_name":"Wedding Photographers",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":221,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/70178988-f84b-48e4-bb38-40200bdf7fab.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":221,
                "album_id":null,
                "comment":"",
                "id":1166,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"foot mehndi design",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/08\/01\/prettiest-foot-mehndi-designs-for-every-kind-of-bride\/\" target=\"_blank\">Prettiest Foot Mehndi Designs For Every Kind Of Bride!<\/a>.<\/p>\r\n",
          "title":"Bridal Feet Mehndi Design",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":6579,
          "swPhotos":null,
          "vendorCategory":"Mehendi Designs",
          "is_pic_verified":true,
          "tag_name":"bridal feet mehndi design,foot mehndi design,bridal feet mehendi ideas,bridal feet mehndi designs,bridal foot mehndi,bridal mehandi,bridal mehendi,floral feet mehendi,foot mehndi designs,jhali mehendi designs,mandala mehndi designs,mehandi ideas,mehendi design ideas,minimalistic feet mehendi designs,morocon style mehndi,toe mehendi designs,trendy henna design,latest henna designs,latest mehendi designs,bridal henna designs,arabic feet mehndi designs,bridal feet henna,bridal feet henna ideas,bridal feet mehndi ideas,easy feet mehendi designs,feet mehandi designs,feet mehndi design ideas,simple feet mehandi designs,small wedding ideas,unique feet mehendi designs,bridal feet arabic mehendi",
          "metaDesc":"Bridal mehndi designs, Bridal mehndi designs for hands, Arabic mehndi designs & Pakistani mehndi designs - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Mehendi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/03870b64-e5fa-9114-48c3-7514dc6b6c2d.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Mother, bride and sister portrait ",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2019\/05\/11\/35-outfit-inspirations-for-mother-of-the-bride-and-groom\/\" target=\"_blank\">35 Outfit Inspirations For Mother Of The Bride And Groom<\/a>.<\/p>\r\n",
          "title":"Mother, bride and sister portrait ",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":3029,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"bridal lehenga,mother,sister,peach bridal lehenga,Bridal Jewellery,red and off white lehenga,bridal hairstyle,Jewellery,Nath,Maang Tikka,bridal outfit ideas,bridal wear trends,family portraits,bridal portraits,wedding photography,wedding picture ideas,bridal bangles,red shawl,winter weddings,smiling bride,wedding inspirations",
          "metaDesc":"Bridal lehenga designs, designer lehenga designs, latest bridal lehenga images & trends - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/26fe083d-69f9-3719-b21e-d28fc4502390.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Colorblind Production",
                "inspiration_id":3029,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/colorblindproduction",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":5684,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"bridalentry",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/12\/29\/intimate-lockdown-wedding-in-ahmedabad\/\" target=\"_blank\">A Cosy Intimate Lockdown Wedding In Ahmedabad With Just 50 People<\/a>.<\/p>\r\n",
          "title":"bridal entry under phoolon ki chadar",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":9054,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Wedding Photography,Unique Ideas",
          "is_pic_verified":true,
          "tag_name":"ahmedabad wedding,lockdown wedding,intimate wedding,small wedding,Real Shaadi,real wedding,bridal lehenga,Floral Lehenga,Pastel Lehenga,Bridal Jewellery,bridal bangles,bridal kalire,bridal entry,wedding photography,phoolon ki chadar",
          "metaDesc":"Browse a variety of wedding photos at ShaadiWish. Search by, color, design and more.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/ca711a99-6bd7-7212-4214-d2f1ad0ecfed.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Alwar",
          "altag":"Groom Portrait",
          "rsId":96,
          "description":"",
          "title":"Dashing Groom Shot",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Palace Wedding",
          "id":5140,
          "swPhotos":null,
          "vendorCategory":"Groom Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"decor ideas,Groom Portrait,stage decor,groom photography,neemrana wedding,groom wear,groom kurta,navy blue grrom kurta,groom outfit,Groom Outfit Ideas,groom photoshoot,wedding photography,Palace Wedding,destination wedding",
          "metaDesc":"Find the latest on groom fashion, trends, photos and ideas to plan your wedding on ShaadiWish. ",
          "rsName":"A Palace Wedding In Neemrana With A Colourful Twist",
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/6778ff10-9dbd-48db-886f-cd1bea2f51c3big.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Candid Bridesmaids Photoshoot Ideas",
          "rsId":null,
          "description":"",
          "title":"Candid Bridesmaids Photoshoot Ideas",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":3206,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"Mehendi,Mehendi Ceremony,bride,bridesmaids,bridesmaids outfit ideas,Outfit Ideas,wedding outfit ideas,bridesmaids photoshoot ideas,candid bridesmaids shot,bride and bridesmaids photoshoot,photoshoot ideas,photography ideas,wedding photography,wedding ideas,wedding trends,Wedding Inspiration",
          "metaDesc":"Browse a variety of wedding pictures and photos at ShaadiWIsh. Search by location, color, theme and more.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Mehendi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/41ad8b34-cf1c-9ee3-a458-ae1321b31c57.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"infinite art",
                "inspiration_id":3206,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":0,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"infinite art",
                   "vendor_category_name":"Wedding Photographers",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":882,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/f18d2f32-59ab-4204-9b6f-8015341a5416.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":882,
                "album_id":null,
                "comment":"",
                "id":5788,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"floral hairstyles",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2019\/12\/27\/best-bridal-hairstyles-2019-we-spotted-on-real-brides\/\" target=\"_blank\">Best Bridal Hairstyles 2019 We Spotted On Real Brides!<\/a>.<\/p>\r\n",
          "title":"Baby Breaths & Carnations In One Hairdo",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":4217,
          "swPhotos":null,
          "vendorCategory":"Make Up and Hair",
          "is_pic_verified":true,
          "tag_name":"bridal hairstyle,bridal hairstyles 2019,Trending Hairstyle,latest bridal hairstyle,wedding hairstyles,hair accessory,floral hairstyle,Carnations,baby breaths,curls,bridal trends,wedding trends,wedding ideas,Wedding Inspiration",
          "metaDesc":"Bridal makeup looks, gorgeous makeup looks, wedding hairstyles, celebrity looks - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Sangeet",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/38840fe8-3c7c-eb27-7d3e-d296d250f267.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Gaurav Chawla",
                "inspiration_id":4217,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/gaurav_chawla_hairstylist\/",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":7409,
                "category":"Bridal Makeup",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Sangeet Stage Decor",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/07\/13\/wedding-stage-decor-ideas\/\" target=\"_blank\">Splendid Wedding Stage Decor Ideas For Your Grand Nuptials<\/a>.<\/p>\r\n",
          "title":" Dreamy Sangeet Stage Setup With Oodles Of Flowers",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Multicultural Weddings",
          "id":6412,
          "swPhotos":null,
          "vendorCategory":"Decor",
          "is_pic_verified":true,
          "tag_name":"sangeet stage setup,sangeet stage decor,couple seating decor,stage decor,decor ideas,wedding decor ideas,decor inspiration,stage decor ideas,floral strings,flower decor,floral decor ideas,couple seating,stage,unique stage decor,couple seating ideas,floral decor,flower decoration,Decor Trends,Wedding decor,engagement decor,decor trends for engagement,engagement stage decor,stage decor inspiration,stage decoration,theme stage decorations,traditional wedding stage decor,wedding decoration,wedding stage d\u00e9cor ideas",
          "metaDesc":"Indian wedding decoration ideas & designs, wedding mandap designs and photos, wedding stage designs & photos and flower decor ideas - get latest & popular designs, ideas & inspirations for your wedding decor.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Sangeet",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/452ccb73-709f-6edd-12c3-c9f103083224.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"personalised lehenga",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2021\/01\/16\/tijara-fort-wedding-with-the-bride-in-beige-lehenga\/\" target=\"_blank\">A Glam Tijara Fort Wedding With The Bride In Beige Lehenga<\/a>.<\/p>\r\n",
          "title":"Bridal Personalised Wedding Dupatta",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Multicultural Weddings",
          "id":9751,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"bridal photoshoot,beige bridal lehenga,Bridal Jewellery,bridal lehenga,Bridal Shot,personalised lehenga,bridal portrait,bride in beige bridal lehenga,destination wedding,destination wedding in tijara fort,Fort Wedding,Kundan Jewellery,Palace Wedding,Real Shaadi,tijara fort wedding,wedding photography",
          "metaDesc":"Explore 1000s of wedding & bridal photos and save ideas for your wedding. Start exploring from Shaadiwish gallery and follow the latest designs and trends to plan a perfect wedding. ",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/b6eee5e5-55d2-791a-3f1c-964eb08c3826.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"bridal hairstyle ideas",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/08\/04\/bridal-hairstyles-with-gajra\/\" target=\"_blank\">Different Ways To Wear A Gajra For A Trendsetter Bridal Look<\/a>.<\/p>\r\n",
          "title":"Beautiful Gajra Braid For Roka Function",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":7181,
          "swPhotos":null,
          "vendorCategory":"Make Up and Hair,Bridal Wear",
          "is_pic_verified":true,
          "tag_name":"bridal hairstyle ideas,Bridal Hairstyles,bridal hairstyles with gajra,bridal trends,Gajra,gajra bridal hairstyles,gajra hairstyles,wedding hairstyles,wedding trends",
          "metaDesc":"Bridal makeup looks, gorgeous makeup looks, wedding hairstyles, celebrity looks - get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Roka",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/185da592-2080-70fe-25bc-4dd69d75d8b8.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Akhil",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2020\/12\/16\/akhil-sachdeva-wedding\/\" target=\"_blank\">#Exclusive: All About Singer Akhil Sachdeva&rsquo;s Wedding In Jaipur<\/a>.<\/p>\r\n",
          "title":"Couple Color Coordinated Outfit",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Multicultural Weddings",
          "id":8811,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Groom Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"matching outfit,couple color coordinated outfit,color coordinated outfit ideas,akhil mehendi ceremony,Mehendi Ceremony,Celebrity Wedding,Mehendi function,Mehendi outfit,mehendi wear,singer wedding,singer akhil sachdeva,destination wedding,destination wedding in jaipur,Jaipur Wedding,kabir singh singer akhil sachdeva,singer akhil sachdeva\u2019s wedding,tanya gulla",
          "metaDesc":"Celebrity wedding pictures and wedding looks, get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Mehendi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/5b85870a-1a07-2b18-d37e-c68d1ff3eaf1.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Camlition Productions",
                "inspiration_id":8811,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":0,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"Camlition Productions",
                   "vendor_category_name":"Wedding Photographers",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":953,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/7e2db798-4c36-4ee0-9f03-1fe2220c63f5.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":953,
                "album_id":null,
                "comment":"",
                "id":9554,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             },
             {
                "city":null,
                "rating":0,
                "vendor_name":"Makeup by Meera Sakhrani",
                "inspiration_id":8811,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":4,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"Makeup by Meera Sakhrani",
                   "vendor_category_name":"Bridal Makeup",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":304,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/117b52bb-eb30-47f3-b61e-bf271d5d33c9.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":304,
                "album_id":null,
                "comment":"",
                "id":9555,
                "category":"Bridal Makeup",
                "vendor_pic_url":null,
                "categoryId":null
             },
             {
                "city":null,
                "rating":0,
                "vendor_name":"Vidya Tikari",
                "inspiration_id":8811,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":5,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"Vidya Tikari",
                   "vendor_category_name":"Bridal Makeup",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":2,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/a49afd0c-57df-4a12-9cb7-38eb45a80034.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":2,
                "album_id":null,
                "comment":"Makeup & hair",
                "id":9557,
                "category":"Bridal Makeup",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Shillim",
          "altag":"Couple Photoshoot",
          "rsId":230,
          "description":"",
          "title":"Joyful Bride & Groom On Their Big Day",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":3666,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Groom Wear,Wedding Photography,Unique Ideas",
          "is_pic_verified":true,
          "tag_name":"couple portrait,bridal lehenga,Groom Outfit Ideas,groom wear,bridal outfit ideas,Bridal Jewellery,bridal makeup ideas,groom wearing necklace,Groom Sherwani,bridal hairstyle ideas,couple outfit ideas,color coordinated outfits,Outdoor Photography,Groom Trends,open hairstyle ideas,groom wearing sunglasses,couple coordinated outfits",
          "metaDesc":"Browse a variety of wedding pictures and photos at ShaadiWIsh. Search by location, color, theme and more.",
          "rsName":"A Majestic Wedding In Shillim With Beautiful Decor By Aash Studio!",
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/3c44813c-2dab-49c7-b97f-b5aaa8ae0a54.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"aashstudio",
                "inspiration_id":3666,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/aashstudio\/",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":6546,
                "category":"Wedding Decorators",
                "vendor_pic_url":null,
                "categoryId":null
             },
             {
                "city":null,
                "rating":0,
                "vendor_name":"whatknotin",
                "inspiration_id":3666,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/whatknotin\/",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":6547,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Newport Coast, CA ",
          "altag":"Ivory Sherwani",
          "rsId":199,
          "description":"",
          "title":"Ivory Sherwani for the Groom",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Muslim Weddings",
          "id":3911,
          "swPhotos":null,
          "vendorCategory":"Groom Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"wedding photography,juttis,groom wear,Groom Sherwani,groom photoshoot,Ivory Sherwani,groom wear ideas,sherwani design ideas,simple sherwani design,Groom Portrait,portrait ideas,photoshoot ideas,photography ideas,wedding ideas,wedding trends,wedding isnpiration",
          "metaDesc":"Find the latest on groom fashion, trends, photos and ideas to plan your wedding on ShaadiWish. ",
          "rsName":"A Gorgeous Pakistani Wedding In California With Beautiful Decor Elements",
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/21d5fec8-579f-45fa-91ff-99652f9a12af.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Warrior And The Gypsy",
                "inspiration_id":3911,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/warriorandthegypsy\/",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":6940,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             },
             {
                "city":null,
                "rating":0,
                "vendor_name":"Pelican Hill Weddings",
                "inspiration_id":3911,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/pelicanhillweddings\/",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":6941,
                "category":"Wedding Venues",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Sri Lanka",
          "altag":"Destination Wedding",
          "rsId":320,
          "description":"",
          "title":"Pool Party For Destination Wedding",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Destination Wedding",
          "id":7394,
          "swPhotos":null,
          "vendorCategory":"Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"wedding photography,destination wedding ideas,Pool Party,Wedding Guests,Outdoor Photography,pool party for destination wedding,destination wedding,pool party ideas",
          "metaDesc":"Browse a variety of wedding pictures and photos at ShaadiWish. Search by location, color, theme and more.",
          "rsName":"A Serene Wedding In Sri Lanka With Picturesque Location And Surroundings",
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Haldi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/9450db2f-7710-45ec-8d7c-c6923ce4b209.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Couple with dogs in Haldi function ",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2019\/05\/18\/pawfect-ways-to-include-pets-at-wedding\/\" target=\"_blank\">We Have Got The &lsquo;Pawfect&rsquo; Ways To Include Pets At Wedding!<\/a>.<\/p>\r\n",
          "title":"Couple with dogs in Haldi function ",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":2937,
          "swPhotos":null,
          "vendorCategory":"Wedding Photography,Unique Ideas",
          "is_pic_verified":true,
          "tag_name":"pets at weddings,pets at indian weddings,dogs at weddings,dog with couple,couple & dog portrait,haldi day,Haldi Ceremony,bride kissing groom,haldi couple portrait,couple portrait,Couple Photoshoot,haldi decor,couple name decor,couple name backdrop,Marigold decor,floral decor",
          "metaDesc":"Browse a variety of wedding pictures and photos at ShaadiWIsh. Search by location, color, theme and more.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Haldi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/9f9e84cc-1a4d-ab8e-904b-30750b6be0a8.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Sikkim",
          "altag":"pre-wedding outfit ideas",
          "rsId":256,
          "description":"",
          "title":"outdoor pre-wedding shoot ideas",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":5342,
          "swPhotos":null,
          "vendorCategory":"Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"Pre Wedding Shoot,couple portrait,groom wear,candid photography,bridal outfit ideas,pre wedding photoshoot ideas,pre wedding outfit ideas,pre wedding location ideas,groom wearing shades",
          "metaDesc":"Explore for the best and latest trends, inspiration and ideas for Pre Wedding Shoot Concepts and Portraits at ShaadiWish.",
          "rsName":"A Romantic Pre-Wedding At Picturesque Locations In Sikkim!",
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Pre-Wedding",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/a6660a38-f0d3-4352-882a-a9f033898f6c.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Razz Films and Photography",
                "inspiration_id":5342,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":0,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"Razz Films and Photography",
                   "vendor_category_name":"Wedding Photographers",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":798,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/b0a7d68e-a424-496d-bb5a-5f69b7284eaf.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":798,
                "album_id":null,
                "comment":"",
                "id":8481,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Kasauli",
          "altag":"Groom on Knees Shot",
          "rsId":221,
          "description":"",
          "title":"Groom on Knees Shot",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Sikh Weddings",
          "id":2321,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear,Groom Wear,Wedding Photography",
          "is_pic_verified":true,
          "tag_name":"couple portrait,Groom Outfit Ideas,bridal outfit ideas,Bridal Jewellery,bridal makeup ideas,diamond jewellery,Groom Sherwani,engagement ceremony,bridal hairstyle ideas,Outdoor Photography,groom on knees,groom kissing bride,Loose Curls,bridal skirt and top,Punjabi wedding,Punjabi Couple,punjabi bride,Punjabi Groom",
          "metaDesc":"Browse a variety of wedding pictures and photos at ShaadiWIsh. Search by location, color, theme and more.",
          "rsName":"A Gorgeous Kasauli Wedding With Awe-Inspiring Wedding Ceremonies And Couple Outfits!",
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Engagement",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/9b4ae93c-cac4-46c3-a5b5-ee55ec467dd9.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"The Wedding Story",
                "inspiration_id":2321,
                "blogPost_id":null,
                "url":"",
                "vendor":{
                   "creation_time":0,
                   "badgeUrl":null,
                   "sub_category":"",
                   "city":null,
                   "rating":5,
                   "no_of_view":0,
                   "vendor_icon_pic_url":null,
                   "starting_price":0,
                   "company_name":"The Wedding Story",
                   "vendor_category_name":"Wedding Photographers",
                   "badgeTitle":null,
                   "rank":0,
                   "currency":null,
                   "id":543,
                   "vendor_pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/1263ea0a-ab18-4e3e-9565-da51b1e93499.png",
                   "region":null,
                   "desc":null,
                   "discount_offered":null
                },
                "vendor_id":543,
                "album_id":null,
                "comment":"",
                "id":4748,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Ravishing Mehendi Outfit",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2019\/07\/17\/new-and-trendy-contemporary-mehendi-outfits-for-2019-brides\/\" target=\"_blank\">New and Trendy Contemporary Mehendi Outfits for 2019 Brides<\/a>.<\/p>\r\n",
          "title":"Ravishing Mehendi Outfit",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":2182,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear",
          "is_pic_verified":true,
          "tag_name":"mehendi day,bride,bridal wear,bridal wear trends,offbeat mehendi outfit,Mehendi outfit,Mehendi outfit ideas,Bridal Jewellery,earrings,bridal portrait,portrait ideas,bridal photoshoot,wedding photography,photography ideas,bridal trends,wedding trends,wedding ideas",
          "metaDesc":"Explore 1000s of wedding & bridal photos and save ideas for your wedding. Start exploring from Shaadiwish gallery and follow latest designs and trends to plan a perfect wedding. ",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Mehendi",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/b24f3128-cbca-0747-85b1-c66249228cdd.jpg",
          "blogId":null,
          "taggedVendors":[
             {
                "city":null,
                "rating":0,
                "vendor_name":"Recall Pictures",
                "inspiration_id":2182,
                "blogPost_id":null,
                "url":"https:\/\/www.instagram.com\/recall_pictures\/?hl=en",
                "vendor":null,
                "vendor_id":null,
                "album_id":null,
                "comment":"",
                "id":4476,
                "category":"Wedding Photographers",
                "vendor_pic_url":null,
                "categoryId":null
             }
          ],
          "colours":null
       },
       {
          "sourceId":0,
          "photoAndTag":null,
          "city":"Jaipur",
          "altag":"Bhumi Padnekar in Black Cocktail Saree",
          "rsId":null,
          "description":"<p>Read more from blog<br \/>\r\n<a href=\"https:\/\/shaadiwish.com\/blog\/2019\/11\/14\/bollywood-celebs-sharing-some-major-ott-cocktail-saree-inspirations-and-how\/\" target=\"_blank\">Bollywood Celebs Sharing Some Major OTT Cocktail Saree Inspirations And How!<\/a>.<\/p>\r\n",
          "title":"Bhumi Padnekar in Classic Black Cocktail Saree",
          "no_of_likes":0,
          "page_id":null,
          "video_url":null,
          "is_like":false,
          "blogUrl":null,
          "theme":"Hindu Weddings",
          "id":3390,
          "swPhotos":null,
          "vendorCategory":"Bridal Wear",
          "is_pic_verified":true,
          "tag_name":"cocktail saree,Cocktail,Sangeet,sangeet outfits,cocktail outfit,sangeet saree,western saree,modern blouse,fancy blouse,fancy saree,Bridesmaid outfit,bridesmaid saree,cocktail bridesmaid outfit,black saree,black cocktail saree,black,bhumi padnekar",
          "metaDesc":"Celebrity wedding pictures and wedding looks, get latest & popular designs, ideas & inspirations for your wedding here at ShaadiWish.",
          "rsName":null,
          "users":null,
          "rsPhotoId":null,
          "no_of_shoot_photo":0,
          "admin_id":0,
          "category":"Cocktail",
          "pic_url":"https:\/\/s3-us-west-2.amazonaws.com\/shaadiwishnewbucket\/6be918c5-ceef-99cc-a120-0e3f87eb4a85.jpg",
          "blogId":null,
          "taggedVendors":null,
          "colours":null
       }
    ]

  return (
    <>
    <Breadcrumb title={"Language"} breadcrumb={breadcrumb} />
    <div className={styles.container}>
      <HeadMeta  title={pageTitle} /> 
      <section className="sv">
        <section className="sv__cn">
          <h2 className="sv__cn__titl">Latest Bridal Makeup Images</h2>
          <h3 className="sv__cn__stitl">Bridal Makeup is surely the most important part of a wedding for every bride-to-be. Just with a few brush strokes, they can magically create that perfect bridal look for your big day. From the stunning and simple South Indian and Marathi bride makeup to gorgoeus and elegant Punajbi and Muslim brides makeup we have got images for all. You can browse through a variety of options and bookmark the ones that you like. If you are looking for smokey eyes, HD makeup or glittery eye bridal makeup, you can find images for that too.</h3>
          <section className="sv__cn__info">
            {photos.map((p,index)=>
              <section className="sv__cn__info_lst">
                <img src={p.pic_url} className="sv__cn__info_lst__img sv__cn__info_lst__img--full" />
                <p className="sv__cn__info_lst__det sv__cn__info_lst__det--noposi">{p.vendorCategory}</p>
              </section>
            )}
          </section>
        </section>
      </section>
    </div>
    <style jsx>
      {
          `
          .sv{padding:45px 0 0;text-align:center;width:100%;}
        .sv__cn{}
        .sv__cn__titl{font-size: 28px; line-height: 39px;font-weight:400; color: #000; margin-bottom: 15px; text-transform: capitalize;}
        .sv__cn__stitl{font-size: 18px; padding:0 15px; line-height: 25px; color: #4c4c4c; margin: 0 auto 20px; font-weight: 400;}
        .sv__cn__info{display: flex; cursor:pointer;align-items: flex-start;flex-wrap: wrap; justify-content:center;}
        .sv__cn__info_lst{position: relative;width: 260px;padding-left: 0; padding-right: 0; margin: 0 5px 15px; overflow: hidden; border: 1px solid #e2e2e2; border-radius: 3px;}
        .sv__cn__info_lst__img{border-radius: 10px; transition: 0.8s; overflow: hidden;height: 171px; aspect-ratio: auto 270 / 171; width: 270px;}
        .sv__cn__info_lst__img:hover{filter: brightness(0.7);}
        .sv__cn__info_lst__det{font-size: 18px; text-align: center; color: #fff; z-index: 21; position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);}
        .sv__cn__info_lst__img--full{border-radius: 0; transition: 0.8s; overflow: hidden;height: 242px; aspect-ratio: auto 260 / 242; width: 260px;    object-fit: contain; object-position: top; }
        .sv__cn__info_lst__img--full:hover{filter: brightness(1);}
        .sv__cn__info_lst__det--noposi{font-size: 18px; line-height: 28px;font-weight: bold;text-align: center; color: #000;margin-top: 10px; margin-bottom: 10px; position: relative; left: auto; top: auto; transform:inherit;    display: block; word-wrap: break-word; text-align: center; display: -webkit-box; -webkit-line-clamp:1; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis;}
        .sv__cn__info_lst__sdet{font-size: 14px; margin-top: 5px; margin-bottom: 20px;color: #4c4c4c; text-transform: capitalize;}
          `
      }
    </style>
    </>
  )
}